from typing import List, Optional

class StrictRedis:
    @classmethod
    def from_url(cls, url: str, db: int = None) -> StrictRedis: ...

    def get(self, name: str) -> Optional[bytes]: ...

    def lindex(self, name: str, index: int) -> Optional[bytes]: ...

    def llen(self, name: str) -> int: ...

    def lrange(self, name: str, start: int, end: int) -> List[bytes]: ...

    def zcard(self, name: str) -> int: ...

    def zrange(self, name: str, start: int, end: int) -> List[bytes]: ...

    def zrank(self, name: str, value: bytes) -> int: ...

    def zscore(self, name: str, value: bytes) -> float: ...
